version: 3


tasks:
  lint:
    desc: Lint the code
    cmds:
      - task fix
      - golint ./...

  fix:
    desc: Fix the code
    cmds:
      - gofmt -w -s .
      - goimports -w .
  update:
    desc: Update the dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
  build:
    desc: Build the binary
    vars:
      os:
        desc: OS to build for
        default: darwin
        sh: echo $(go env GOOS)
      arch:
        desc: Architecture to build for
        default: arm64
        sh: echo $(go env GOARCH)
      prod:
        default: false

    cmds:
      - |
        if [ "{{.prod}}" = "true" ]; then
         CGO_ENABLED=0 GOOS={{.os}} GOARCH={{.arch}} go build -ldflags="-s -w" -o aalm .
        else
        GOOS={{.os}} GOARCH={{.arch}} go build -o aalm .
        fi
        
    
